### ISSUE TITLE
default settings for all new saves

### ISSUE THREAD

**Issue by Dziq84** [bbpak/stardew-valley-mods#62]
hello,  would be very nice to have this mod load default settings for all new created saves.  I playing mostly in coop and I want to be sure that other players don't 'cheating' too much by showing all npc's while they even don't meet them - its ruining experience from game.
I already changed key from TAB to smth else,  so they will never found that there is hidden menu on map view heh. Only these default settings are missing :(

by default settings I mean something like that: (tried adding values in globals.json (these marked with gray background), but every new save clears all of these settings :/  )
.
.

![notepad++_2020-10-22_02-10-43](https://user-images.githubusercontent.com/13541407/96803175-cf4c1e00-140b-11eb-9a0b-f0f080375d4a.jpg)
.
hope it is possible to change that..  Thanks in advance. cheers

**Comment by bbpak** [comment]
Moved most settings to globals.json, only the conditions for showing NPCs are per-save.
