### ISSUE TITLE
Failed to show all npcs when playing in multiplayer

### ISSUE THREAD

**Issue by KrisCris** [bbpak/stardew-valley-mods#64]
### Exception:
[NPC Map Locations] This mod failed in the GameLoop.UpdateTicked event. Technical details:
System.NullReferenceException: 
   In NPCMapLocations.ModMain.LocationToMap(String locationName, Int32 tileX, Int32 tileY, Dictionary`2 CustomMapVectors, List`1 LocationBlacklist, Boolean isPlayer) Location C:\Users\bbouh\Projects\stardew-valley-mods\NPCMapLocations\ModMain.cs: line 936
   In NPCMapLocations.ModMain.UpdateFarmers() Location C:\Users\bbouh\Projects\stardew-valley-mods\NPCMapLocations\ModMain.cs: line 886
   In NPCMapLocations.ModMain.UpdateMarkers(Boolean forceUpdate) Location C:\Users\bbouh\Projects\stardew-valley-mods\NPCMapLocations\ModMain.cs: line 684
   In NPCMapLocations.ModMain.GameLoop_UpdateTicked(Object sender, UpdateTickedEventArgs e) Location C:\Users\bbouh\Projects\stardew-valley-mods\NPCMapLocations\ModMain.cs: cs 467
   In StardewModdingAPI.Framework.Events.ManagedEvent`1.<>c__DisplayClass16_1.<Raise>b__2() Location C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs: line 138
   In StardewModdingAPI.Framework.PerformanceMonitoring.PerformanceMonitor.Track(String collectionName, String sourceName, Action action) Location C:\source\_Stardew\SMAPI\src\SMAPI\Framework\PerformanceMonitoring\PerformanceMonitor.cs: line 87

**Comment by bbpak** [comment]
Fix by @boleanly
