### ISSUE TITLE
How to run Function CustomNpcMarkerOffsets through another DLL?

### ISSUE THREAD

**Issue by asnise** [bbpak/stardew-valley-mods#67]
How to run Function CustomNpcMarkerOffsets Without modifying globals.json file, can you suggest me the code? I'm looking for a way to run a different function from another mod through my mod.

-Excuse me if sometimes I don't know anything about it. I'm not good at languages.

**Comment by bbpak** [comment]
Reworked the config to integrate with other mods primarily through Content Patcher.
