### ISSUE TITLE
Possible rewrite for Content Patcher?

### ISSUE THREAD

**Issue by itsbenter** [bbpak/stardew-valley-mods#68]
Hi bouhm,
Thanks for the mod! I'm wondering would it be possible to make the data for "CustomNpcMarkerOffsets" targetable with Content Patcher instead of having it as part of Config?
This will make it easier for the custom NPCs modders to ensure the NPC marker will be correct (add the data for the marker themselves with CP) while simplifying the installation for the user (Removing the need to edit the config manually).

The same perhaps could be done with the CustomMapLocations in customlocations.json

I imagine NPC map location will function as it is for the vanilla game while Custom NPC marker and the information for the custom map will all be handled through CP by the respective modder.

I imagine it'll be some work to do, but perhaps u might be interested.

**Comment by bbpak** [comment]
Reworked the config to integrate with other mods primarily through Content Patcher.
