### ISSUE TITLE
PrimaryText/SecondaryText not shown on map

### ISSUE THREAD

**Issue by wamc2017** [bbpak/stardew-valley-mods#71]
Hi,

I tried adding support for the Ridgeside Village mod through contentpatcher with version 2.6.0 and it seems like PrimaryText/SecondaryText getting ignored when using MapTooltip. It always shows  the assigned [LocationName] on the map itself.
I attached my test content pack down below just in case.

Thanks for looking into it.

[[CP} Ridge Worldmap.zip](https://github.com/bbpak/stardew-valley-mods/files/6028930/CP.Ridge.Worldmap.zip)

**Comment by wamc2017** [comment]
I can only guess what's the issue, but I think `tooltip.Key `should be `text` in this line if it's a custom tooltip.

https://github.com/bbpak/stardew-valley-mods/blob/ce5a30e09a8a57905fdb7f24610a35d26b37992d/NPCMapLocations/ui/ModMapPage.cs#L112

**Comment by bbpak** [comment]
You were right, just fixed it! Thanks.
